name: meetly
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  google_sign_in: ^7.2.0
  flutter_svg: ^2.2.2
  go_router: ^17.0.0
  pretty_dio_logger: ^1.4.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  rxdart: ^0.28.0
  geolocator: ^14.0.2
  image_picker: ^1.2.0
  socket_io_client: ^3.0.1
  google_maps_flutter: ^2.14.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  json_serializable: ^6.11.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Black.ttf
        - asset: assets/fonts/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend-ExtraBold.ttf
        - asset: assets/fonts/Lexend-ExtraLight.ttf
        - asset: assets/fonts/Lexend-Light.ttf
        - asset: assets/fonts/Lexend-Medium.ttf
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-SemiBold.ttf
        - asset: assets/fonts/Lexend-Thin.ttf

# ðŸ‘‡ Add this at the END of the file
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
